language: c
sudo: false
compiler: gcc
os:
- linux
branches:
  only:
  - master
  - ulua-docgen
notifications:
  email: false
script:
- chmod -R +xrw .
- cd docgen
- ". ./build_docs.sh"

after_success:
- cd ..
- ". ./deploy.sh"
