language: c
sudo: false
compiler: gcc
os:
- linux
branches:
  only:
  - master
notifications:
  email: false
script:
- git clone -b docgen --single-branch https://github.com/thegrb93/StarfallEx.git docgen
- chmod -R +xrw .
- cd docgen
- ". ./build_docs.sh"

after_success:
- cd ..
- ". ./deploy.sh"
